
CREATE SCHEMA IF NOT EXISTS BOOKPUP DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE BOOKPUP ;

CREATE TABLE book (
  ID int(11) NOT NULL,
  NAME varchar(45) NOT NULL,
  FREQUENCY varchar(45) DEFAULT NULL,
  AUTHOR varchar(45) DEFAULT NULL,
  PUBLISHING_DATE date DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE edition (
  ID int(11) NOT NULL,
  EDITION_NAME varchar(45) DEFAULT NULL,
  EDITION_DATE date DEFAULT NULL,
  BOOK_ID int(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_BOOK_ID_idx (BOOK_ID),
  CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES book (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE address (
  ID int(11) NOT NULL,
  STREET_1 varchar(45) DEFAULT NULL,
  CITY varchar(45) DEFAULT NULL,
  STATE varchar(45) DEFAULT NULL,
  COUNTRY varchar(45) DEFAULT NULL,
  PINCODE int(11) DEFAULT NULL,
  STREET_2 varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE subscriber (
  ID int(11) NOT NULL,
  NAME varchar(45) DEFAULT NULL,
  MOBILE_NUMBER varchar(45) DEFAULT NULL,
  ADDRESS_ID int(11) DEFAULT NULL,
  GROUP_CODE varchar(45) DEFAULT NULL,
  CODE varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE subscription (
  ID int(11) NOT NULL,
  SUBSCRIPTION_YEAR int(11) DEFAULT NULL,
  SUBSCRIPTION_DATE date DEFAULT NULL,
  SUBSCRIPTION_EXPIRED_DATE date DEFAULT NULL,
  SUBSCRIBER_ID int(11) DEFAULT NULL,
  Book_ID int(11) DEFAULT NULL,
  subscription_group varchar(45) DEFAULT NULL,
  subscription_number int(11) DEFAULT NULL,
  subscription_code varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY Unique_key (Book_ID,subscription_code),
  KEY fk_SUBSCRIBE_INFO_SUBSCRIBER1_idx (SUBSCRIBER_ID),
  KEY fk_SUBSCRIBE_INFO_Book1_idx (Book_ID),
  CONSTRAINT fk_SUBSCRIBE_INFO_Book1 FOREIGN KEY (Book_ID) REFERENCES book (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_SUBSCRIBE_INFO_SUBSCRIBER1 FOREIGN KEY (SUBSCRIBER_ID) REFERENCES subscriber (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

 

CREATE TABLE catagory (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CODE varchar(45) DEFAULT NULL,
  VALUE int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);



