CREATE TABLE address (
  ID int(11) NOT NULL,
  STREET_1 varchar(45) DEFAULT NULL,
  STREET_2 varchar(45) DEFAULT NULL,
  CITY varchar(45) DEFAULT NULL,
  STATE varchar(45) DEFAULT NULL,
  COUNTRY varchar(45) DEFAULT NULL,
  PINCODE int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE shop (
  id int(11) NOT NULL,
  SHOP_NUMBER varchar(45) DEFAULT NULL,
  SQARE_FEET decimal(10,0) DEFAULT NULL,
  GROUP_ID int(11) DEFAULT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE shop_group (
  id int(11) NOT NULL,
  GROUP_NAME varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE tenant (
  ID int(11) NOT NULL,
  SHOP_NAME varchar(45) DEFAULT NULL,
  BOOKING_DATE date DEFAULT NULL,
  PAYMENT_MODE varchar(45) DEFAULT NULL,
  DUE_AMOUNT double DEFAULT NULL,
  SHOP_ID int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);
